#!/usr/bin/env node
/**
 * AI 工具配置生成器（SSOT：docs/agent-config/ → 各工具目录）。
 *
 * HARNESS_SYNC_TMPL_ID: 0.6.9
 * HARNESS_ENG_VERSION: 0.6.9
 *
 * 用法：
 *   node scripts/agent-config/sync.mjs          # 生成/刷新所有工具目录（幂等）
 *   node scripts/agent-config/sync.mjs --check  # 只校验漂移，有差异时退出码 1
 *
 * 约定：
 * - 手改只发生在 docs/agent-config/；已启用工具的 rules/hooks/mcp/settings/skills
 *   与 CLAUDE.md 均为生成物（含 GENERATED 标记），手改会被本脚本覆盖。
 * - rules 的 .mdc frontmatter 为 Cursor 原生格式；qoder/claude 生成时 strip 元数据，
 *   path-scoped 语义以正文自然语言保留。trae / workbuddy(codebuddy) 保留 alwaysApply /
 *   globs / description（官方项目规则 frontmatter；CodeBuddy CLI 亦认 paths）。
 * - Codex：不做 .mdc 镜像。命令策略走 docs/agent-config/codex/rules/*.rules → .codex/rules/；
 *   MCP → .codex/config.toml.example；hooks → .codex/hooks.json + codex-adapter；
 *   skills → .agents/skills/（不全量 prune 用户自建 skill 目录）。
 * - 各工具目录中未被本脚本管理的内容（如 docs/harness-eng/harness-meta.yaml、
 *   遗留 .cursor/harness-meta.yaml、mcp.local.json 等运行时数据）不受影响。
 * - 协议族：cursor → hooks.json（Cursor 事件）；claude/qoder/workbuddy → settings.json hooks
 *   （Claude 系）；trae → .trae/hooks.json。均经 claude-adapter 翻译统一脚本。
 *   Codex 族：.codex/hooks.json + codex-adapter.js。
 * - 托管 rules 目录（.cursor/.trae/.qoder/.claude/.codebuddy/rules）里不在本脚本 plan
 *   的文件会被当 stale 清理。这是故意的：L3+/L5 全量镜像宿主不再写 1x-contract-sync.md；
 *   宿主侧 00-harness-ssot 孤儿也不属于 plan（由 SSOT docs/agent-config/rules/00-harness-ssot.mdc
 *   分发）。缺 00 时先 land/render 把 SSOT 指针写上再 sync，勿 git restore 宿主孤儿。
 * - CodeBuddy 0.6.4：rules 改为扁平 `.codebuddy/rules/<stem>.md`（保留 FM）。旧布局
 *   `.codebuddy/rules/<name>/RULE.mdc` 及空目录会在托管前缀下被 prune（故意迁移清理）。
 * - 不生成 settings.local.json / .codebuddy/agents/（非目标）。hooks 改 settings.json 后须在
 *   IDE `/hooks` 面板确认应用（仅保存文件 ≠ 热生效）。$CODEBUDDY_PROJECT_DIR 仍可用。
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const SSOT = path.join(ROOT, "docs", "agent-config");
const CHECK_ONLY = process.argv.includes("--check");
const HARNESS_SYNC_TMPL_ID = "0.6.9";
const HARNESS_ENG_VERSION = "0.6.9";

/** 本仓启用的 AI 工具（land/upgrade 时按 Q_AI_TOOL 渲染；手改请改这里再跑 sync） */
const AI_TOOLS = ["cursor","claude"];
const has = (t) => AI_TOOLS.includes(t);

const HEADER_MD =
  "> ⚠️ 本文件由 `node scripts/agent-config/sync.mjs` 生成，请勿手改；SSOT：`docs/agent-config/`。\n\n";
const HEADER_JSON =
  "GENERATED by scripts/agent-config/sync.mjs — DO NOT EDIT. SSOT: docs/agent-config/";
const SKILLS_MARKER =
  "# GENERATED\n\n本目录由 `node scripts/agent-config/sync.mjs` 生成，请勿手改；SSOT：`docs/agent-config/skills/`。\n";

/** rel（正斜杠）→ string|Buffer */
const plan = new Map();

function put(rel, content) {
  plan.set(rel, content);
}
function putJson(rel, obj) {
  put(rel, JSON.stringify(obj, null, 2) + "\n");
}
function readSsot(...segs) {
  return fs.readFileSync(path.join(SSOT, ...segs), "utf8");
}
function ssotExists(...segs) {
  return fs.existsSync(path.join(SSOT, ...segs));
}
function walk(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

// ---------- rules ----------

const FM_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

function parseRule(raw) {
  const m = raw.match(FM_RE);
  if (!m) return { fm: {}, body: raw };
  const fm = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (kv) fm[kv[1]] = kv[2].trim();
  }
  return { fm, body: raw.slice(m[0].length) };
}

function loadRules() {
  const dir = path.join(SSOT, "rules");
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".mdc"))
    .map((f) => ({ name: f, raw: fs.readFileSync(path.join(dir, f), "utf8"), ...parseRule(fs.readFileSync(path.join(dir, f), "utf8")) }));
}

/** Cursor .mdc → 宿主 .md。trae/workbuddy 保留 FM；qoder/claude strip 并降级为正文提示。 */
function toHostMd(rule, host) {
  if (host === "trae" || host === "workbuddy") {
    return rule.raw.replace(FM_RE, (m) => m + "\n" + HEADER_MD);
  }
  const bits = [];
  if (rule.fm.alwaysApply === "true") bits.push("> 适用范围：始终应用\n");
  if (rule.fm.globs) bits.push(`> 适用路径：\`${rule.fm.globs}\`\n`);
  const head = bits.length ? bits.join("\n") + "\n" : "";
  return HEADER_MD + head + rule.body;
}

function planRules() {
  for (const rule of loadRules()) {
    const withHeader = rule.raw.replace(FM_RE, (m) => m + "\n" + HEADER_MD);
    // cursor：原生 .mdc（frontmatter 保留）
    if (has("cursor")) put(`.cursor/rules/${rule.name}`, withHeader);
    // qoder / claude：纯 .md（path 作用域降级为正文提示）
    if (has("qoder")) {
      put(`.qoder/rules/${rule.name.replace(/\.mdc$/, ".md")}`, toHostMd(rule, "qoder"));
    }
    if (has("trae")) {
      put(`.trae/rules/${rule.name.replace(/\.mdc$/, ".md")}`, toHostMd(rule, "trae"));
    }
    if (has("claude")) {
      put(`.claude/rules/${rule.name.replace(/\.mdc$/, ".md")}`, toHostMd(rule, "claude"));
    }
    // codebuddy：扁平 .md（保留 FM；对齐官方 CLI rules/*.md）
    if (has("workbuddy")) {
      put(`.codebuddy/rules/${rule.name.replace(/\.mdc$/, ".md")}`, toHostMd(rule, "workbuddy"));
    }
  }
}

// ---------- hooks ----------

function buildClaudeStyleEvents(cfg, tool) {
  const events = {};
  const ids = [];
  const dir = `.${tool === "workbuddy" ? "codebuddy" : tool}`;
  for (const h of cfg.hooks) {
    const t = h.targets?.[tool];
    if (!t) continue;
    ids.push(h.id);
    const command =
      h.id === "commit-gate"
        ? `node ${dir}/hooks/${h.script} --claude`
        : `node ${dir}/hooks/claude-adapter.js ${t.adapter} ${h.script}`;
    (events[t.event] ||= []).push({
      ...(t.matcher ? { matcher: t.matcher } : {}),
      hooks: [{ type: "command", command, timeout: t.timeout || 8 }],
    });
  }
  return { events, ids, dir };
}

function planHooks() {
  const scriptsDir = path.join(SSOT, "hooks");
  const allScripts = fs.existsSync(scriptsDir)
    ? fs.readdirSync(scriptsDir).filter((f) => f.endsWith(".js"))
    : [];

  // Codex 可不依赖 hooks.config.json（有默认事件表）
  if (has("codex")) {
    planCodexHooks(allScripts, scriptsDir);
  }

  if (!ssotExists("hooks", "hooks.config.json")) return;
  const cfg = JSON.parse(readSsot("hooks", "hooks.config.json"));

  const copy = (toolDir, ids, needAdapter) => {
    for (const s of allScripts) {
      const isAdapter = s === "claude-adapter.js";
      const used = cfg.hooks.some((h) => h.script === s && ids.includes(h.id));
      if ((isAdapter && needAdapter) || (!isAdapter && used)) {
        put(`${toolDir}/hooks/${s}`, fs.readFileSync(path.join(scriptsDir, s)));
      }
    }
  };

  // cursor：hooks.json 按 Cursor 事件分组
  if (has("cursor")) {
    const events = {};
    const ids = [];
    for (const h of cfg.hooks) {
      const t = h.targets?.cursor;
      if (!t) continue;
      ids.push(h.id);
      (events[t.event] ||= []).push({
        command: `node .cursor/hooks/${h.script}`,
        ...(t.matcher ? { matcher: t.matcher } : {}),
        ...(t.timeout ? { timeout: t.timeout } : {}),
        failClosed: false,
        ...(t.loop_limit ? { loop_limit: t.loop_limit } : {}),
      });
    }
    if (ids.length) {
      putJson(`.cursor/hooks.json`, { _generated: HEADER_JSON, version: 1, hooks: events });
      copy(".cursor", ids, false);
    }
  }

  // claude / qoder / workbuddy：Claude 系 hooks 写入 settings.json
  for (const tool of ["claude", "qoder", "workbuddy"]) {
    if (!has(tool)) continue;
    const { events, ids, dir } = buildClaudeStyleEvents(cfg, tool);
    if (!ids.length) continue;
    const needAdapter = ids.some((id) => id !== "commit-gate");
    const base =
      (tool === "qoder" || tool === "workbuddy") && ssotExists("settings.json")
        ? JSON.parse(readSsot("settings.json"))
        : {};
    const out = {
      _generated: HEADER_JSON,
      ...base,
      hooks: events,
    };
    // workbuddy：缺 permissions 时补最小默认；已有 permissions 不覆盖（不 wipe 用户/SSOT）
    if (tool === "workbuddy" && !out.permissions) {
      out.permissions = {
        defaultMode: "default",
        deny: ["Read(./.env)", "Read(./secrets/**)"],
      };
    }
    putJson(`${dir}/settings.json`, out);
    copy(dir, ids, needAdapter);
  }

  // trae：项目级 .trae/hooks.json（Claude 系嵌套格式）
  if (has("trae")) {
    const { events, ids } = buildClaudeStyleEvents(cfg, "trae");
    if (ids.length) {
      const needAdapter = ids.some((id) => id !== "commit-gate");
      putJson(".trae/hooks.json", { _generated: HEADER_JSON, version: 1, hooks: events });
      copy(".trae", ids, needAdapter);
    }
  }
}

/** Codex hooks：优先 SSOT codex/hooks.json，否则默认 PreToolUse(^Bash$)+Stop */
function planCodexHooks(allScripts, scriptsDir) {
  if (ssotExists("codex", "hooks.json")) {
    put(".codex/hooks.json", readSsot("codex", "hooks.json"));
  } else {
    const defaultHooks = {
      _generated: HEADER_JSON,
      description: "harness-eng Codex hooks (fail-open)",
      hooks: {
        PreToolUse: [
          {
            matcher: "^Bash$",
            hooks: [
              {
                type: "command",
                command:
                  'node "$(git rev-parse --show-toplevel)/.codex/hooks/codex-adapter.js" commit-gate superpowers-commit-gate.js',
                timeout: 12,
                statusMessage: "Checking Bash commit gate",
              },
            ],
          },
        ],
        Stop: [
          {
            hooks: [
              {
                type: "command",
                command:
                  'node "$(git rev-parse --show-toplevel)/.codex/hooks/codex-stop-checklist.js"',
                timeout: 8,
                statusMessage: "Delivery soft check",
              },
            ],
          },
        ],
      },
    };
    putJson(".codex/hooks.json", defaultHooks);
  }
  for (const s of allScripts) {
    if (s === "claude-adapter.js") continue;
    put(`.codex/hooks/${s}`, fs.readFileSync(path.join(scriptsDir, s)));
  }
  if (ssotExists("hooks", "codex-adapter.js")) {
    put(".codex/hooks/codex-adapter.js", readSsot("hooks", "codex-adapter.js"));
  }
  if (ssotExists("hooks", "codex-stop-checklist.js")) {
    put(".codex/hooks/codex-stop-checklist.js", readSsot("hooks", "codex-stop-checklist.js"));
  }
}

// ---------- mcp / settings ----------

function redactEnvToNames(env) {
  if (!env || typeof env !== "object") return [];
  return Object.keys(env).filter(Boolean);
}

function escapeTomlString(s) {
  return JSON.stringify(String(s));
}

/** Inline MCP JSON → Codex TOML (no secrets). */
function jsonServersToCodexToml(doc) {
  const servers = doc?.mcpServers || {};
  const lines = [
    "# GENERATED from docs/agent-config/mcp — do not put secrets here",
    "# Project .codex/config.toml loads only when the workspace is trusted",
    `# ${HEADER_JSON}`,
    "",
  ];
  for (const [name, server] of Object.entries(servers)) {
    if (!server || typeof server !== "object") continue;
    const key = name.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push(`[mcp_servers.${key}]`);
    if (server.command) {
      lines.push(`command = ${escapeTomlString(server.command)}`);
      if (Array.isArray(server.args)) {
        lines.push(`args = [${server.args.map(escapeTomlString).join(", ")}]`);
      }
    } else if (server.url) {
      lines.push(`url = ${escapeTomlString(server.url)}`);
      if (server.bearer_token_env_var) {
        lines.push(
          `bearer_token_env_var = ${escapeTomlString(server.bearer_token_env_var)}`
        );
      }
    }
    const names = redactEnvToNames(server.env);
    if (names.length) {
      lines.push(`env_vars = [${names.map(escapeTomlString).join(", ")}]`);
    }
    lines.push("enabled = false");
    lines.push('default_tools_approval_mode = "prompt"');
    lines.push("");
  }
  return lines.join("\n");
}

function planMcp() {
  // servers.json 为可选 SSOT（含密时属 vendored_shared 团队约定；example_only 仓勿建）
  if (ssotExists("mcp", "servers.json")) {
    const servers = JSON.parse(readSsot("mcp", "servers.json"));
    if (has("cursor")) putJson(".cursor/mcp.json", { _generated: HEADER_JSON, ...servers });
    // qoder / claude / workbuddy 官方主路径：仓库根 .mcp.json
    if (has("claude") || has("qoder") || has("workbuddy")) {
      putJson(".mcp.json", { _generated: HEADER_JSON, ...servers });
    }
    // trae：项目级 .trae/mcp.json
    if (has("trae")) putJson(".trae/mcp.json", { _generated: HEADER_JSON, ...servers });
    // Codex：脱敏投影到 example（真密勿入库）
    if (has("codex")) {
      put(".codex/config.toml.example", jsonServersToCodexToml(servers));
    }
  }
  if (ssotExists("mcp", "servers.example.json")) {
    const example = JSON.parse(readSsot("mcp", "servers.example.json"));
    if (has("cursor")) putJson(".cursor/mcp.json.example", { _generated: HEADER_JSON, ...example });
    if (has("claude") || has("qoder") || has("workbuddy")) {
      putJson(".mcp.json.example", { _generated: HEADER_JSON, ...example });
    }
    if (has("trae")) putJson(".trae/mcp.json.example", { _generated: HEADER_JSON, ...example });
    if (has("codex") && !plan.has(".codex/config.toml.example")) {
      put(".codex/config.toml.example", jsonServersToCodexToml(example));
    }
  }
}

function planCodexRules() {
  if (!has("codex")) return;
  const dir = path.join(SSOT, "codex", "rules");
  if (!fs.existsSync(dir)) return;
  for (const file of walk(dir)) {
    const rel = path.relative(dir, file).split(path.sep).join("/");
    if (!rel.endsWith(".rules")) continue;
    put(`.codex/rules/${rel}`, fs.readFileSync(file));
  }
}

function planSettings() {
  // qoder/workbuddy settings 已在 planHooks 与 hooks 合并写出；此处补无 hooks 时的落盘
  if (!ssotExists("settings.json")) return;
  const settings = JSON.parse(readSsot("settings.json"));
  if (has("cursor")) putJson(".cursor/settings.json", { _generated: HEADER_JSON, ...settings });
  if (has("qoder") && !plan.has(".qoder/settings.json")) {
    putJson(".qoder/settings.json", { _generated: HEADER_JSON, ...settings });
  }
  if (has("workbuddy") && !plan.has(".codebuddy/settings.json")) {
    const out = { _generated: HEADER_JSON, ...settings };
    if (!out.permissions) {
      out.permissions = {
        defaultMode: "default",
        deny: ["Read(./.env)", "Read(./secrets/**)"],
      };
    }
    putJson(".codebuddy/settings.json", out);
  }
}

// ---------- skills ----------

function planSkills() {
  const src = path.join(SSOT, "skills");
  if (!fs.existsSync(src)) return;
  const dirs = [
    has("cursor") && ".cursor",
    has("qoder") && ".qoder",
    has("claude") && ".claude",
    has("trae") && ".trae",
    has("workbuddy") && ".codebuddy",
  ].filter(Boolean);
  for (const file of walk(src)) {
    const rel = path.relative(src, file).split(path.sep).join("/");
    for (const dir of dirs) {
      put(`${dir}/skills/${rel}`, fs.readFileSync(file));
    }
    // Codex 官方路径 .agents/skills（全量分发；不进 MANAGED_DIRS 以免 prune 用户自建）
    if (has("codex")) {
      put(`.agents/skills/${rel}`, fs.readFileSync(file));
    }
  }
  for (const dir of dirs) {
    put(`${dir}/skills/GENERATED.md`, SKILLS_MARKER);
  }
  if (has("codex")) {
    put(
      ".agents/skills/GENERATED.md",
      "# GENERATED\n\nCodex skills SSOT：`docs/agent-config/skills/` → `.agents/skills/`（`sync.mjs`）。\n" +
        "本文件标记托管树；用户自建 skill 目录不会被 prune。\n"
    );
  }
}

// ---------- CLAUDE.md 桥接 ----------

function planClaudeMd() {
  if (!has("claude")) return;
  put(
    "CLAUDE.md",
    "<!-- " + HEADER_JSON + " -->\n\n" +
      "@AGENTS.md\n\n" +
      "rules / hooks / MCP / skills 的单一真相源为 `docs/agent-config/`，本文件与 `.claude/` 等工具目录均为生成物；手改请改到 SSOT 后跑 `node scripts/agent-config/sync.mjs`。\n"
  );
}

// ---------- 写盘 / 校验 ----------

const MANAGED_DIRS = [
  has("cursor") && ".cursor/rules",
  has("cursor") && ".cursor/hooks",
  has("cursor") && ".cursor/skills",
  has("qoder") && ".qoder/rules",
  has("qoder") && ".qoder/hooks",
  has("qoder") && ".qoder/skills",
  has("claude") && ".claude/rules",
  has("claude") && ".claude/hooks",
  has("claude") && ".claude/skills",
  has("trae") && ".trae/rules",
  has("trae") && ".trae/hooks",
  has("trae") && ".trae/skills",
  has("workbuddy") && ".codebuddy/rules",
  has("workbuddy") && ".codebuddy/hooks",
  has("workbuddy") && ".codebuddy/skills",
  has("codex") && ".codex/hooks",
  has("codex") && ".codex/rules",
].filter(Boolean);

function staleFiles() {
  const stale = [];
  for (const dir of MANAGED_DIRS) {
    const abs = path.join(ROOT, dir);
    if (!fs.existsSync(abs)) continue;
    for (const file of walk(abs)) {
      const rel = path.relative(ROOT, file).split(path.sep).join("/");
      if (!plan.has(rel)) stale.push(rel);
    }
  }
  return stale;
}

/** 文本比对忽略 CRLF/LF（Windows autocrlf / HEADER 注入混用时避免假漂移） */
function sameText(diskBuf, content) {
  const norm = (s) => s.replace(/\r?\n/g, "\n");
  return norm(diskBuf.toString("utf8")) === norm(String(content));
}

function apply() {
  const diffs = [];
  for (const [rel, content] of plan) {
    const abs = path.join(ROOT, rel);
    const disk = fs.existsSync(abs) ? fs.readFileSync(abs) : null;
    const same =
      disk !== null &&
      (Buffer.isBuffer(content) ? disk.equals(content) : sameText(disk, content));
    if (!same) diffs.push(rel);
    if (!CHECK_ONLY && !same) {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
    }
  }
  const stale = staleFiles();
  if (!CHECK_ONLY) {
    for (const rel of stale) fs.rmSync(path.join(ROOT, rel));
    // 迁出旧 RULE.mdc 目录后清掉空文件夹（尤其 .codebuddy/rules/<name>/）
    for (const dir of MANAGED_DIRS) pruneEmptyDirs(dir);
  }
  return { diffs, stale };
}

function pruneEmptyDirs(relDir) {
  const abs = path.join(ROOT, relDir);
  if (!fs.existsSync(abs)) return;
  for (const e of fs.readdirSync(abs, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const child = `${relDir}/${e.name}`.replace(/\\/g, "/");
    pruneEmptyDirs(child);
    const childAbs = path.join(ROOT, child);
    if (fs.existsSync(childAbs) && fs.readdirSync(childAbs).length === 0) {
      fs.rmdirSync(childAbs);
    }
  }
}

planRules();
planHooks();
planMcp();
planCodexRules();
planSettings();
planSkills();
planClaudeMd();

const { diffs, stale } = apply();
if (CHECK_ONLY) {
  if (diffs.length || stale.length) {
    console.error(`[agent-config] 漂移 ${diffs.length} 处，过期文件 ${stale.length} 处：`);
    for (const f of [...diffs, ...stale.map((s) => s + " (stale)")]) console.error(`  - ${f}`);
    console.error("请执行：node scripts/agent-config/sync.mjs");
    process.exit(1);
  }
  console.log(`[agent-config] 无漂移（${plan.size} 个生成物与 SSOT 一致；${HARNESS_SYNC_TMPL_ID}/${HARNESS_ENG_VERSION}）`);
} else {
  console.log(
    `[agent-config] 生成完成：写入 ${diffs.length} 个文件，清理 ${stale.length} 个过期文件，共管理 ${plan.size} 个生成物`
  );
}
